### ISSUE TITLE
Controller dan URL (Ujicoba di Linux)

### ISSUE THREAD

**Issue by dikiwidia** [fadhiilrachman/SimpegCI#1]
Ada sedikti masalah yang terjadi ketika saya mencoba menginstal ini di direktori web lokal saya. Masalah tersebut yaitu dari URL yang digunakan memakai _lowercase_ sedangkan dalam Linux kami membaca URL dengan _case-sensitive_ mengikuti penamaan berkas dan kelas yang digunakan.

Contoh
**Linux** http://localhost/simpegci/**Data_Master**/admin

**Comment by auliarahmed** [comment]
Bener banget, tinggal dirubah aja menjadi Data_master
udah gitu aja

**Comment by farizmuhamadislam** [comment]
masih tetep dirubah filenya jadi huruf kecil jadi data_master.php tetep 404 not found ini di linux juga

**Comment by fadhiilrachman** [comment]
Thanks sudah report issue.

Boleh dicoba pakai docker ya.
